### PR TITLE
repo: Updated README.md to include additional package

### PR DESCRIPTION
**Pull request by Paulls20**

### CODE REVIEW

**Comment by fizzyade** [comment]
Hi Paul, I already made one of your changes, (the missing package), once this is changed from draft I will merge in!

I see where the setcap is now, I was searching in code.

Thank you for these changes.

**Comment by Paulls20** [comment]
I'm closing this PR, since you already made these changes.

**Comment by fizzyade** [comment]
I only made the one change, I'd like to merge in your other changes so you can be credited.

**Comment by fizzyade** [comment]
I've merged it in for you.  

Apologies for jumping ahead and making the initial change, I really appreciate people like yourself taking the time to help with the project, I will take all and any help that I can get.

**Pull request merged**
