### PR TITLE
Build RPMs the Red Hat Way (TM)

### PR DESCRIPTION
**Pull request by AaronDMarasco**
RPM is no longer a fancy tarball; instead it is built with the proper scripts, C++ flags, dependency searches, etc, etc.

Additionally, a lot of the "infrastructure" stuff from `deploy.py` got taken out into a common library to not clutter the top-level dirs as well as allow it to be reused in the RPM part.

> ❯ ./deploy.py --rpm --version 2021.02
> Deployment process started at 2021-02-21 17:48:44.920279
> 
> > Checking for curl... [✓]
> > Creating rpm package...
> > Checking for rpmbuild [✓]
> > Checking for rpmdev-setuptree [✓]
> > Removing existing rpmbuild subtree [✓]
> > Creating rpmbuild subtree [✓]
> > Creating specfile [✓]
> > Creating tarball [✓]
> > Calling rpmbuild (logged to rpmbuild.log) [✓]
> 
> rpm package at "bin/x86_64/Deploy/rpm/pingnoo-2021.02-1.x86_64.rpm" is ready for distribution.
> 
> Total time taken to perform deployment was 1m50s.

### CODE REVIEW

**Comment by fizzyade** [comment]
I'm going to merge this in over the weekend, I'm actually taking parts of this for some other python scripts.

The other scripts are pretty much very specific to me, but I want to incorporate your changes and methods into it.  The scripts are basically to set up the development environments for various releases of Linux distributions under LXC containers.  It means I have repeatable mechanisms of regenerating the development sandboxes very easily if I need to.

The sandboxes contain the development environment and teamcity build agents, it's just extending what I currently do here for macOS, Windows and Linux Appimages, in conjunction with your RPM changes I have fedora 32 and 33 containers set up and ready to build.

**Comment by AaronDMarasco** [comment]
> I'm actually taking parts of this for some other python scripts.

That's the point. ;) Glad you can use it.

**Comment by fizzyade** [comment]
I'm just building binaries to fix a bug, but I'm looking to merge this in.  There's an issue with the deployment on macOS, the CMAKE_PREFIX_PATH needs to be set to ..Qt/5.15.2 but, the deployment script needs to know about the computer because the actual qt binaries are in ..Qt/5.15.2/clang_54, I'm not sure the best way of fixing this whether it's to add a --compiler switch which allows the compiler to be set so that the correct qt path is available.

Any thoughts?

**Comment by AaronDMarasco** [comment]
> CMAKE_PREFIX_PATH needs to be set to ..Qt/5.15.2 but, the deployment script needs to know about the computer because the actual qt binaries are in ..Qt/5.15.2/clang_54

I don't see `CMAKE_PREFIX_PATH` anywhere in this changeset... but one thing you could do is tweak the `find_qt` to maybe get the compiler version and then try a bunch of permutations looking for `os.path.exists`? I don't know a lot about CMake but there's prolly some magic it can do to detect. https://www.kdab.com/using-cmake-with-qt-5/ maybe?

**Comment by fizzyade** [comment]
tHere's a good reason you can't see it, I haven't actually fixed it yet, I just hand modified the build on teamcity to get the binaries built so I could upload it.

It's set on the call the cmake, so that's another reason you can;t see it, you have to tell cmake where qt is and the most flexible way is to pass it on the command line.

cmake <src> -DCMAKE_PREFIX_PATH=/home/adrian/Qt/5.15.2

cmake needs that path, but as I mentioned, other tools need to know the actual compiler, in this case on macOS it's clang_64.  

To be honest, I could pretty much safely just hard code that into the script because it's unliikly that anybody would use any other compiler, I certainly won't.

I think I've just talked myself into hardcoding it.

**Comment by fizzyade** [comment]
I realised I was talking rubbish, this is what happens when you write stuff in the early hours.  You do pass in the compiler to the CMAKE_PREFIX_PATH.

**Comment by fizzyade** [comment]
I merged this @AaronDMarasco and TeamCity was still happy, so that's good!  I'm going to add the fedora 33 and 32 builds to my CI config.

**Comment by fizzyade** [comment]
@AaronDMarasco I have intentions of making this more generic (although still only for Qt based applications).

For each platform, the output "generator" is a "plugin" (not sure what the term is on Python), it would make it more flexible for this application, but also usable by anybody without having to delve into the specifics how a deployment is performed.

**Comment by fizzyade** [comment]
@AaronDMarasco I am in the process of setting up a build agent for teamcity to automatically build the RPM's.

I hit a couple of snags, firstly the rpm builder doesn't like the -(branch) on the version, so I have removed that in the rpm script.

The second issue is that I'm trying r33 first, I'm now getting an error saying that the rpm depends on qt5-devel, but there's no such package, or at least I can't install it with dnf.

Any ideas?

There are the packages I have on the build agent:

dnf -y group install "C Development Tools and Libraries"
dnf -y install cmake
dnf -y install git
dnf -y install python-qt5-rpm-macros
dnf -y install qt5-devel
dnf -y install qt5-qtbase-devel
dnf -y install qt5-linguist
dnf -y install rpm-build
dnf -y install rpmdevtools
dnf -y install qt5-qtquickcontrols2-devel
dnf -y install dbus-devel
dnf -y install vim

**Comment by fizzyade** [comment]
I replaced qt5-devel with qt5-qtbase-devel in the rpm spec, and now I get errors thrown by cmake because it's using the same build tree.

RPM build errors:
[21:42:00]
[Step 3/3] + umask 022
[21:42:00]
[Step 3/3] + cd /opt/teamcity-agent/work/47d95f567ff3ef24/rpmbuild/BUILD
[21:42:00]
[Step 3/3] + cd /opt/teamcity-agent/work/47d95f567ff3ef24/rpmbuild/BUILD
[21:42:00]
[Step 3/3] + rm -rf pingnoo-2021.03.16
[21:42:00]
[Step 3/3] + /usr/bin/tar -xof /opt/teamcity-agent/work/47d95f567ff3ef24/rpmbuild/SOURCES/pingnoo-2021.03.16.tar
[21:42:00]
[Step 3/3] + STATUS=0
[21:42:00]
[Step 3/3] + '[' 0 -ne 0 ']'
[21:42:00]
[Step 3/3] + cd pingnoo-2021.03.16
[21:42:00]
[Step 3/3] + /usr/bin/chmod -Rf a+rX,u+w,g-w,o-w .
[21:42:00]
[Step 3/3] + mkdir build
[21:42:00]
[Step 3/3] + cd build
[21:42:00]
[Step 3/3] + CFLAGS='-O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection'
[21:42:00]
[Step 3/3] + export CFLAGS
[21:42:00]
[Step 3/3] + CXXFLAGS='-O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection'
[21:42:00]
[Step 3/3] + export CXXFLAGS
[21:42:00]
[Step 3/3] + FFLAGS='-O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -I/usr/lib64/gfortran/modules'
[21:42:00]
[Step 3/3] + export FFLAGS
[21:42:00]
[Step 3/3] + FCFLAGS='-O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -I/usr/lib64/gfortran/modules'
[21:42:00]
[Step 3/3] + export FCFLAGS
[21:42:00]
[Step 3/3] + LDFLAGS='-Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld '
[21:42:00]
[Step 3/3] + export LDFLAGS
[21:42:00]
[Step 3/3] + LT_SYS_LIBRARY_PATH=/usr/lib64:
[21:42:00]
[Step 3/3] + export LT_SYS_LIBRARY_PATH
[21:42:00]
[Step 3/3] + CC=gcc
[21:42:00]
[Step 3/3] + export CC
[21:42:00]
[Step 3/3] + CXX=g++
[21:42:00]
[Step 3/3] + export CXX
[21:42:00]
[Step 3/3] + /usr/bin/cmake -S . -B x86_64-redhat-linux-gnu -DCMAKE_C_FLAGS_RELEASE:STRING=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE:STRING=-DNDEBUG -DCMAKE_Fortran_FLAGS_RELEASE:STRING=-DNDEBUG -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DCMAKE_INSTALL_PREFIX:PATH=/usr -DINCLUDE_INSTALL_DIR:PATH=/usr/include -DLIB_INSTALL_DIR:PATH=/usr/lib64 -DSYSCONF_INSTALL_DIR:PATH=/etc -DSHARE_INSTALL_PREFIX:PATH=/usr/share -DLIB_SUFFIX=64 -DBUILD_SHARED_LIBS:BOOL=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_SKIP_RPATH=True ..
[21:42:00]
[Step 3/3] CMake Error: The current CMakeCache.txt directory /opt/teamcity-agent/work/47d95f567ff3ef24/rpmbuild/BUILD/pingnoo-2021.03.16/CMakeCache.txt is different than the directory /opt/teamcity-agent/work/47d95f567ff3ef24 where CMakeCache.txt was created. This may result in binaries being created in the wrong place. If you are not sure, reedit the CMakeCache.txt
[21:42:00]
[Step 3/3] error: Bad exit status from /var/tmp/rpm-tmp.RjpfUW (%prep)
[21:42:00]
[Step 3/3]     Bad exit status from /var/tmp/rpm-tmp.RjpfUW (%prep)

**Comment by AaronDMarasco** [comment]
I don't know off-hand, sorry. I am not familiar with Teamcity at all, and not sufficient with CMake enough to diagnose that better. It looks like Teamcity might be messing with certain variables (like `RPM_BUILD_ROOT`) - can you have it dump the env when it starts? 

I don't remember what Fedora my laptop is, but I can try upgrading it to 33 (not a VM). But I've had lots of problems with my wifi so it might die we'll see. Maybe tomorrow after work; if you had tried this yesterday, I was off all day today...

**Comment by fizzyade** [comment]
I did get a little further, to the point of compiling….but for some reason it can’t even get past the compiler checks.  I’m not familiar with fedora at all, so I think it’s going to be a bit of reading and trial and error.

**Comment by AaronDMarasco** [comment]
<Let's move this conversation to #33>

**Pull request merged**
